### ISSUE TITLE
nasm required

### ISSUE THREAD

**Issue by plicease** [Getty/p5-alien-ffmpeg#2]
Maybe use --disable-yasm if nasm/yasm isn't in the path, or maybe a Alien::nasm would be helpful. I'm happy to help if features in Alien::Base might make either of these proposals easier. 

Tried to open this in rt but got a "queue not found error"

**Comment by plicease** [comment]
This should be fixed with #3.  How about doing a CPAN release?

**Comment by plicease** [comment]
I'm willing to do the release if you don't have the time.

**Comment by zmughal** [comment]
I believe that this can be closed now: <https://metacpan.org/release/WOUTER/Alien-ffmpeg-0.104/source/Build.PL#L12>.

**Comment by yoe** [comment]
yeah, this has been fixed
