### ISSUE TITLE
change configure_requires to Alien::Base::ModuleBuild

### ISSUE THREAD

**Issue by plicease** [Getty/p5-alien-ffmpeg#4]
For the rationale, please see Perl5-Alien/Alien-Base#157

All you need to do is make sure you have the latest version of the [Alien] plugin and do a release.

**Comment by plicease** [comment]
Please let me know if I can help out with this PR. I would like to split Alien::Base::ModuleBuild into its own distribution and this change will keep this module from breaking.

**Comment by yoe** [comment]
Should be fixed with 1257f4da14b4473c1602661b4d60267b8ad3b24f

**Comment by zmughal** [comment]
@yoe, I'm wondering if you are handling new CPAN releases?

**Comment by yoe** [comment]
I am planning to do that, yes.

Unfortunately I've been too busy with other things recently, but my time is clearing up now and I'll look at this soon.

**Comment by yoe** [comment]
Upload done now, should be available shortly.
